config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'items#index'
  # item routes
  resources :items
  patch "/items/:id", to: "items#update", as: 'update_item'
  get "/user_items", to: "items#userlistings", as: 'user_items' #search for user's own listings

  # cart routes
  resources :carts, only: [:create]
  get '/carts/history', to: 'carts#history'
  get '/cart', to: 'carts#active'
  post '/carts/:id/checkout', to: 'carts#checkout', as: 'checkout_cart' # change cart status to purchased, create new cart, update user's cart to new cart

  # cart_item routes
  delete '/cart_item/:id', to: 'cart_item#destroy', as: 'destroy_cart_item' # redirect back to cart show
  post '/cart_item', to: 'cart_item#create', as: 'create_cart_item' # no redirect, just flash a message
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items
  has_many :items, through: :cart_items
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :cart

  validates :item, uniqueness: { scope: :cart }
  # validates :item, uniqueness: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_many :cart_items, dependent: :destroy
  validate :size_check
  validate :category_check
  has_one_attached :image_url
  validates :image_url, presence: true

  scope :by_price, -> (min_price, max_price) do
    where('price >= ? AND price <= ?', min_price.to_f, max_price.to_f)
  end

  scope :by_location, -> (location) do
    where('location ILIKE ?', location)
  end

  scope :by_categories, -> (categories) do
    where('categories ILIKE ?', categories)
  end

  scope :by_size, -> (size_array) do
    where("size ILIKE ANY ( array[?] )", size_array)
  end

  scope :by_condition, -> (condition_array) do
    where("condition ILIKE ANY ( array[?] )", condition_array)
  end

  scope :by_keyword, -> (given_keyword) do
    sql_query = " \
      items.name ILIKE ? \
      OR items.brand ILIKE ? \
      OR items.categories ILIKE ? \
      OR items.location ILIKE ? \
      OR items.condition ILIKE ANY ( array[?] )\
      OR items.size ILIKE ANY ( array[?] ) \

    "
    where(sql_query, "%#{given_keyword}%", "%#{given_keyword}%", "%#{given_keyword}%", "%#{given_keyword}%", given_keyword, given_keyword)
  end

  private

  def size_check
    if size.present? && ['S','M','L','XL','Fluffy'].include?(size) == false
      errors.add(:size, "Must be S, M, L, XL, or Fluffy!")
    end
  end

  def category_check
    if categories.present? && ['Tops', 'Bottoms', 'Accessories', 'Bags'].include?(categories) == false
      errors.add(:categories, "S, M, L, XL, Fluffy!")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :items
  has_many :carts
  has_many :cart_items, through: :carts
  

  # user.active_cart_items
  def active_cart_items
    carts.last.items
  end

  # user.purchased_carts
  def purchased_carts
    carts.where("status = 'inactive'")
  end

  def active_cart
    carts.where("status = 'active'").first
  end

  # user.for_sale_items
  def for_sale_items
    items
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/cart_item_controller.rb
class CartItemController < ApplicationController
  def destroy
    @cart_item = CartItem.find(params[:id])
    @cart_item.delete
    redirect_to cart_path
  end

  def create
    @item = Item.find(params[:item])
    @user = User.find(params[:user])
    if @user.carts.count === 0
      Cart.create!(user: @user, status: 'active')
    end
    new_item = CartItem.new(cart: @user.active_cart, item: @item)
    if new_item.save
      flash.alert = "Item added to cart"
      redirect_back(fallback_location: root_path)
    else
      flash.alert = "You already have that item in your cart!"
      redirect_back(fallback_location: root_path)
    end
  end


end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:checkout]
  def active
    if current_user.carts.count === 0
      Cart.create!(user: current_user, status: 'active')
    end
    @cart = current_user.active_cart
  end

  def checkout
    if @cart.items.count <= 0
      flash.alert = "Cart is empty!"
      redirect_back(fallback_location: root_path)
    else
      @cart.update(status: 'inactive')
      Cart.create(status: 'active', user: @cart.user)
      @cart.items.each do |item|
        item.update(is_sold: true)
      end
      flash.alert = "Cart checked out"
      redirect_to cart_path
    end
  end

  def history
    @carts = current_user.purchased_carts
  end

  private

  def set_cart
    @cart = Cart.find(params[:id])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  has_scope :by_price, using: %i[min_price max_price], type: :hash
  has_scope :by_keyword , using: %i[given_keyword], type: :hash
  has_scope :by_categories
  has_scope :by_size, using: %i[size_array], type: :hash
  has_scope :by_location
  has_scope :by_condition, using: %i[condition_array], type: :hash

  def index
    @items = apply_scopes(Item).all
    @items = @items.where(is_sold: false)
  end

  def show
    @item = Item.find(params[:id])
  end

  def userlistings
    @items = Item.where(user: current_user)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.user = current_user
    if @item.save
      flash.alert = "Item listed!"
      redirect_to user_items_path
    else
      render 'new'
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to user_items_path
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to user_items_path
  end

  private

  def item_params
    params.require(:item).permit(:name, :description, :price, :brand, :categories, :image_url, :location, :size, :condition)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/carts/active.html.erb
<div class="container">
  <% if @cart.items.count > 0 %>
    <div class="container">
      <div class="row border p-2 rounded my-5">
        <div class="col-12">
          <p class="text-center">Your Cart</p>
        </div>
      </div>
      <div class="row border p-2 rounded mb-2">
        <div class="col-2">
          Item
        </div>
        <div class="col-4">
          Description
        </div>
        <div class="col-4">
          Details
        </div>
        <div class="col-2">
          Price
        </div>
      </div>
      <% @cart.items.each do |item| %>
        <% cart_item = CartItem.find_by(item: item, cart: @cart) %>
        <%= render 'shared/cart_item_card', item: item, cart_item: cart_item %>
      <% end %>
    </div>
    <div class="d-flex justify-content-between">
      <%= link_to 'Continue shopping', root_path, class: "btn border btn-light" %>
      <%= link_to 'Checkout', checkout_cart_path(@cart), method: :post, class: "btn btn-dark" %>
    </div>
  <% else %>
    <div class="container">
      <div class="row border p-2 rounded my-5">
        <div class="col-12">
          <p class="text-center">Your cart is currently empty... but not for long!</p>
        </div>
      </div>
    </div>
    <div class="d-flex justify-content-between">
      <%= link_to 'Continue shopping', root_path, class: "btn border btn-light" %>
      <%= link_to 'Checkout', checkout_cart_path(@cart), method: :post, class: "btn btn-dark d-none" %>
    </div>
  <% end %>
</div>

app/views/carts/history.html.erb
<div class="container">
  <% if @carts.count > 0 %>
    <% @carts.each do |cart| %>
      <div class="container">
        <div class="row border p-2 rounded my-5">
          <div class="col-12">
            <p class="text-center">Ordered on <%= cart.updated_at.strftime('%d %b %Y') %></p>
          </div>
        </div>
        <div class="row border p-2 rounded mb-2">
          <div class="col-2">
            Item
          </div>
          <div class="col-4">
            Description
          </div>
          <div class="col-4">
            Details
          </div>
          <div class="col-2">
            Price
          </div>
        </div>
        <% cart.items.each do |item| %>
          <% cart_item = CartItem.find_by(item: item, cart: cart) %>
          <%= render 'shared/cart_item_card', item: item, cart_item: cart_item %>
        <% end %>
      </div>
    <% end %>
  <% else %>
    <div class="container">
        <div class="row border p-2 rounded my-5">
          <div class="col-12">
            <p class="text-center">You have not placed any orders</p>
          </div>
        </div>
      </div>
      <div class="d-flex justify-content-between">
        <%= link_to 'Continue shopping', root_path, class: "btn border btn-light" %>
      </div>
  <% end %>
</div>

app/views/items/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-6">
      <%= cl_image_tag @item.image_url.key, class:"w100", crop: :fill %>
    </div>
    <div class="col-6">
      <%= simple_form_for [@item] do |f| %>
      <%= f.input :name %>
      <%= f.input :price %>
      <%= f.input :brand %>
      <%= f.input :size , collection: ['S','M','L','XL','Fluffy'], include_blank: false %>
      <%= f.input :condition , collection: ['Very good condition', 'Good condition', 'Fair condition', 'Never worn', 'Never worn, with tag'], include_blank: false %>
      <%= f.input :location , collection: ['Bangkok', 'Jakarta', 'Manila', 'Singapore'], include_blank: false %>
      <%= f.input :categories , collection: ['Tops', 'Bottoms', 'Accessories', 'Bags'], include_blank: false %>
      <%= f.submit "Save changes", class: "btn btn-dark", id: "edit_item_submit" %>
      <%= link_to "Back to listings", items_path, class: "btn btn-dark"  %>
      <% end %>
    </div>
  </div>
</div>

app/views/items/index.html.erb
<h1 class='border bg-light p-3 text-center'>Discover <%= params[:by_keyword] %></h1>

<div class="categories-bar d-flex justify-content-center p-4">
<%= link_to 'Tops', items_path(:by_keyword => 'Tops'), class:'text-black nav-link mx-3' %>
<%= link_to 'Bottoms', items_path(:by_keyword => 'Bottoms'), class:'text-black nav-link mx-3' %>
<%= link_to 'Accessories', items_path(:by_keyword => 'Accessories'), class:'text-black nav-link mx-3' %>
<%= link_to 'Bags', items_path(:by_keyword => 'Bags'), class:'text-black nav-link mx-3' %>
</div>

<div class="container">
  <div class="row">
    <div class="col-3">
      <div class="filter">
        <form action="/items" class="mb-1 py-2">
          <input type="number" class="form-control mt-3" placeholder="Min price" name="by_price[min_price]" >
          <input type="number" class="form-control mt-3" placeholder="Max price" name="by_price[max_price]" >
          <input type="submit" class="btn btn-dark btn-block mt-3" value="Filter by price">
        </form>
      </div>
      <div class="filter">
        <form action="/items" class="mb-1 py-2">
        <div class="form-check">
          <input type="checkbox" id="size1" class="form-check-input" name="by_keyword[given_keyword][]" value="S">
          <label class="form-check-label" for="size1">S (<%= Item.all.where(size: 'S').count %>)</label>
        </div>
        <div class="form-check">
          <input type="checkbox" id="size2" class="form-check-input" name="by_keyword[given_keyword][]" value="M">
          <label class="form-check-label" for="size2">M (<%= Item.all.where(size: 'M').count %>)</label>
        </div>
        <div class="form-check">
          <input type="checkbox" id="size3" class="form-check-input" name="by_keyword[given_keyword][]" value="L">
          <label class="form-check-label" for="size3">L (<%= Item.all.where(size: 'L').count %>)</label>
        </div>
        <div class="form-check">
          <input type="checkbox" id="size4" class="form-check-input" name="by_keyword[given_keyword][]" value="XL">
          <label class="form-check-label" for="size4">XL (<%= Item.all.where(size: 'XL').count %>)</label>
        </div>
        <div class="form-check">
          <input type="checkbox" id="size5" class="form-check-input" name="by_keyword[given_keyword][]" value="Fluffy">
          <label class="form-check-label" for="size5">Fluffy (<%= Item.all.where(size: 'Fluffy').count %>)</label>
        </div>
          <input type="submit" class="btn btn-dark btn-block mt-3" value="Filter by size">
        </form>
      </div>
      <div class="filter">
        <form action="/items" class="mb-1 py-2">
        <div class="form-check">
          <input class="form-check-input" type="radio" id="location1" name="by_keyword" value="Bangkok">
          <label class="form-check-label" for="location1">Bangkok (<%= Item.all.where(location: 'Bangkok').count %>)</label>
        </div>
        <div class="form-check">
          <input class="form-check-input" type="radio" id="location2" name="by_keyword" value="Jakarta">
          <label class="form-check-label" for="location2">Jakarta (<%= Item.all.where(location: 'Jakarta').count %>)</label>
        </div>
        <div class="form-check">
          <input class="form-check-input" type="radio" id="location3" name="by_keyword" value="Manila">
          <label class="form-check-label" for="location3">Manila (<%= Item.all.where(location: 'Manila').count %>)</label>
        </div>
        <div class="form-check">
          <input class="form-check-input" type="radio" id="location4" name="by_keyword" value="Singapore">
          <label class="form-check-label" for="location4">Singapore (<%= Item.all.where(location: 'Singapore').count %>)</label>
        </div>
          <input type="submit" class="btn btn-dark btn-block mt-3" value="Filter by location">
        </form>
      </div>
      <div class="filter">
        <form action="/items" class="mb-1 py-2">
          <div class="form-check">
            <input type="checkbox" id="condition1" class="form-check-input" name="by_keyword[given_keyword][]" value="Very good condition">
            <label class="form-check-label" for="condition1">Very good condition (<%= Item.all.where(condition: 'Very good condition').count %>)</label>
          </div>
          <div class="form-check">
            <input type="checkbox" id="condition2" class="form-check-input" name="by_keyword[given_keyword][]" value="Good condition">
            <label class="form-check-label" for="condition2">Good condition (<%= Item.all.where(condition: 'Good condition').count %>)</label>
          </div>
          <div class="form-check">
            <input type="checkbox" id="condition3" class="form-check-input" name="by_keyword[given_keyword][]" value="Fair condition">
            <label class="form-check-label" for="condition3">Fair condition (<%= Item.all.where(condition: 'Fair condition').count %>)</label>
          </div>
          <div class="form-check">
            <input type="checkbox" id="condition4" class="form-check-input" name="by_keyword[given_keyword][]" value="Never worn">
            <label class="form-check-label" for="condition4">Never worn (<%= Item.all.where(condition: 'Never worn').count %>)</label>
          </div>
          <div class="form-check">
            <input type="checkbox" id="condition5" class="form-check-input" name="by_keyword[given_keyword][]" value="Never worn, with tag">
            <label class="form-check-label" for="condition5">Never worn, with tag (<%= Item.all.where(condition: 'Never worn, with tag').count %>)</label>
          </div>
            <input type="submit" class="btn btn-dark btn-block mt-3" value="Filter by condition">
        </form>
      </div>
    </div>
    <div class="cards col-6">
      <% @items.each do |item| %>
        <%= render 'shared/item_card', item: item %>
      <% end %>
    </div>
    <div class="col-3">
    <blockquote class="twitter-tweet"><p lang="en" dir="ltr">R we SAFU today</p>&mdash; tanztanzfarben (@tanztanzfarben) <a href="https://twitter.com/tanztanzfarben/status/1465477137314377730?ref_src=twsrc%5Etfw">November 30, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
    </div>
  </div>
</div>

app/views/items/listed.html.erb
<div class="container">
    <ol>
      <% @items.each do |item| %>
        <% if item.user == current_user %>
          <li>
            <%= item.name %>
            <%= item.description %>
            <%= item.price %>
            <%= item.brand %>
            <%= item.is_sold ? "Sold" : "Not sold" %>
            <%= link_to "Details", item_path(item) %>
          </li>
          <% end %>
      <% end %>
    </ol>
  </div>

app/views/items/new.html.erb
<div class="container">
  <div class="d-flex justify-content-center">
    <div class="col-8 my-5">
      <%= simple_form_for (@item) do |f| %>
      <%= f.input :name %>
      <%= f.input :price %>
      <%= f.input :brand %>
      <%= f.input :size , collection: ['S','M','L','XL','Fluffy'], include_blank: false %>
      <%= f.input :categories , collection: ['Tops', 'Bottoms', 'Accessories', 'Bags'], include_blank: false %>
      <%= f.input :condition , collection: ['Very good condition', 'Good condition', 'Fair condition', 'Never worn', 'Never worn, with tag'], include_blank: false %>
      <%= f.input :location , collection: ['Bangkok', 'Jakarta', 'Manila', 'Singapore'], include_blank: false %>
      <%= f.input :image_url, as: :file %>
      <%= f.submit "List item", class: "btn btn-dark", id: "new_item_submit" %>
      <%= link_to "Back to listings", items_path, class: "btn btn-dark"  %>
      <% end %>
    </div>
  </div>
</div>

app/views/items/show.html.erb
<div class="container">
  <div class='text-center mt-3'>
    <h2>
      <%= @item.brand %>
    </h2>
    <h3>
      <%= @item.name %>
    </h3>
  </div>
  <div>
    <div class="row justify-content-center">
      <%= cl_image_tag @item.image_url.key, crop: :fill, class: 'w100' %>
    </div>
    <div class="row justify-content-center">
      <div class="col-8 py-3">
        <p>Size: <%= @item.size %></p>
        <p>$<%= @item.price %></p>
        <p>Condition: <%= @item.condition %></p>
        <p><%= @item.location %>, from the seller <i><%= @item.user.email %></i></p>
        <% if current_user.carts.count > 0 && current_user.active_cart.items.include?(@item) %>
          <p>Item has been added to cart</p>
        <% else %>
          <%= link_to create_cart_item_path( user: current_user.id, item: @item.id), method: :post, class: 'btn cart btn-block', id: 'add-to-cart' do %>
            <i class="fas fa-cart-plus"></i> Add to cart
          <% end %>
        <% end %>

        <% if current_user == @item.user %>
        <%= link_to edit_item_path(@item), method: :get, class: 'btn btn-dark btn-block' do %>
          <i class="fas fa-edit"></i> Edit
        <% end %>
        <%= link_to item_path(@item), method: :delete, class: 'btn btn-dark btn-block' do %>
          <i class="fas fa-trash"></i> Delete
        <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/items/userlistings.html.erb
<h1 class='border bg-light p-3 text-center'>Your Listings</h1>
<div class="container">
  <div class="cards row">
      <% @items.each do |item| %>
        <%= render 'shared/item_card', item: item %>
      <% end %>
  </div>
  <%= link_to 'Add new listing', new_item_path, class: "btn btn-dark m-2"  %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VestiaireClone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <link rel="stylesheet" href="https://kit-pro.fontawesome.com/releases/v5.15.3/css/pro.min.css" data-mutate-approach="sync">
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

<%= link_to "Products", new_item_path %>

app/views/shared/_cart_item_card.html.erb
<div class="row border rounded p-2 mb-3">
  <div class="col-2">
    <%= link_to image_tag(item.image_url, class: "img-fluid", alt:"img"), item_path(item) %>
  </div>
  <div class="col-4">
    <p><%= item.brand %><br><%= item.categories %></p>
  </div>
  <div class="col-4">
    <p>Size: <%= item.size %><br><%= item.name %></p>
  </div>
  <div class="col-2">
    <div class="d-flex">
      <p>$<%= item.price %></p>
      <% if cart_item.cart.status == 'active' %>
        <%= link_to content_tag(:i, '', :class => "fas fa-trash ml-2"), destroy_cart_item_path(cart_item), method: :delete %>
      <% end %>
    </div>
  </div>

</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <div class="row">
    <div class="col-6">
      <ul class="list-unstyled text-left text-white">
        <li><a class="text-white" href="">About Us</a></li>
        <li><a class="text-white" href="">Sell an Item </a></li>
        <li><a class="text-white" href="">Join Us</a></li>
        <li><a class="text-white" href="">Team</a></li>
      </ul>
    </div>
  </div>
  <ul class="navigation d-flex justify-content-center p-0">
    <li class="nav-item"><a href="" class="nav-link"><i class="fab fa-instagram fa-lg "></i></a></li>
    <li class="nav-item"><a href="" class="nav-link"><i class="fab fa-facebook fa-lg "></i></a></li>
    <li class="nav-item"><a href="" class="nav-link"><i class="fab fa-pinterest-p fa-lg "></i></a></li>
    <li class="nav-item"><a href="" class="nav-link"><i class="fab fa-youtube fa-lg "></i></a></li>
  </ul>
  <div class="copyright container blockquote-footer">
    <div class="d-flex justify-content-center">Singapore - English - UK - S$ - SGD</div>
    <div class="d-flex justify-content-center">This company meets the highest verified standards of social and environmental transparency, and accountability.</div>
    <div class="d-flex justify-content-center">Copyright 2021 VestiaireClone LeWagon Limited. All Rights Reserved.</div>
  </div>
</footer>

app/views/shared/_item_card.html.erb
  <div class="card p-3 m-2">
    <%= link_to item_path(item) do %>

      <div class="d-flex justify-content-center">
        <%= cl_image_tag item.image_url.key, class: 'w100', crop: :fill %>
      </div>

      <div class="pl-3">

        <div><strong><%= item.brand %></strong></div>
        <div><%= item.name %></div>
        <div>Size <%= item.size %></div>
        <div><strong>$<%= item.price %></strong></div>
        <%# hide add to cart button if item is already in cart  %>

        <% if current_user.carts.count > 0 && current_user.active_cart.items.include?(item) %>
          <p>Added to cart</p>
        <% else %>
          <div>
            <i class="fas fa-shopping-cart"></i>
            <%= link_to "Add to cart", create_cart_item_path( user: current_user.id, item: item.id), method: :post, id: "add-to-cart"%>
          </div>
        <% end %>

      </div>
    <% end %>
  </div>

app/views/shared/_navbar.html.erb
<!-- As a link -->
<nav class="navbar navbar-expand-sm navbar-light bg-light">
  <%= link_to root_path, class: "navbar-brand mx-auto" do %>
    <i class="fas fa-angle-down fa-3x black"></i>
  <% end %>
</nav>
<nav class="navbar navbar-expand-sm navbar-light bg-light">
  <%= form_tag items_path, class: "form-inline", method: :get do %>
    <%= text_field_tag :by_keyword,
      params[:by_keyword],
      class: "form-control mr-sm-2",
      placeholder: "Discover our collection"
    %>
    <%= submit_tag "Search", class: "btn btn-ghost my-2 my-sm-0" %>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <%# show if not signed in %>
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Sell an item', new_item_path, class: 'black btn btn-dark'  %>
        </li>
        <li class="nav-item dropdown mx-5">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Your listings", user_items_path, class: "dropdown-item" %>
            <%= link_to "Order History", carts_history_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
        <li class="nav-item">
          <%= link_to cart_path, class: "nav-link" do %>
            <% if current_user.carts.count > 0 && current_user.active_cart.items.count > 0 %>
              <i class="fas fa-shopping-cart fa-lg">
                <span id='cart-count' class="badge badge-pill badge-dark", style="background-color:#FF5A26; color:black"><%= current_user.active_cart.items.count %></span>
              </i>
            <% else %>
              <i class="fas fa-shopping-cart fa-lg"></i>
            <% end %>
          <% end %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Sign in', new_user_session_path, class: 'nav-link'  %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link'  %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>